# Visualisation

mesh_files:
  denso_trolley:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/Assy_Fixing_Cartbase.STL
      material:
        name: "LightGrey_denso_trolley"
        color: "0.89 0.91 0.93 1.0"
    collision:
      box:
        size: "0.8 0.8 0.86"
        origin: "0 0 -0.43"

  denso_base_link:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/denso_base_link.STL
      material:
        name: "Grey_denso_base_link"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/denso/denso_base_link.STL

  denso_J1:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link1.STL
      material:
        name: "Grey_denso_J1"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link1.STL

  denso_J2:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link2.STL
      material:
        name: "Grey_denso_J2"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link2.STL

  denso_J3:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link3.STL
      material:
        name: "Grey_denso_J3"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/denso/denso_link3.STL

  denso_J4:
    visual:
      cylinder:
        radius: 0.02
        length: 0.04
      material:
        name: "Grey_denso_J4"
        color: "0.7 0.7 0.7 1.0"
    collision:
      cylinder:
        radius: 0.02
        length: 0.04

  denso_screwdriver:
    visual:
      mesh:
        package: descriptions
        path: meshes/denso/denso_screwdriver.STL
      material:
        name: "Grey_denso_screwdriver"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/denso/denso_screwdriver.STL

  vision_feeder:
    visual:
      mesh:
        package: descriptions
        path: meshes/vision/vision_feeder.STL
      material:
        name: "Orange_vision_feeder"
        color: "0.95 0.55 0.0 1.0"
    collision:
      mesh:
        package: descriptions
        path: meshes/vision/vision_feeder.STL
      